name: Build .NET project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./EcommerceApi/EcommerceApi.csproj

      - name: Build project
        run: dotnet build ./EcommerceApi/EcommerceApi.csproj --no-restore

